@startuml
!theme reddress-lightorange
'skinparam linetype ortho'
caption Схема навигации
scale 2.0
component [Главная страница] as mainPage
component [Автомобили] as cars
component [Автомобиль] as car
component [Добавить автомобиль] as addCar
component [Марки] as automodels
component [Марка] as automodel
component [Добавить марку] as addAutomodel
component [Клиенты] as clients
component [Клиент] as client
component [Добавить клиентa] as addClient
component [Заказы] as contracts
component [Заказ] as contract
component [Добавить заказ] as addContract


mainPage -d-> cars: Список автомобилей
mainPage -d-> clients : Список клиентов
mainPage -d-> contracts : Список заказов
mainPage -d-> automodels : Список марок

automodels -d-> automodel : Конкретная марка
cars -d-> car: Конкретный автомобиль
clients -d-> client : Конкретный клиент
contracts -d-> contract : Конкретный заказ

automodels -d-> addAutomodel : Добавить марку
cars -d-> addCar: Добавить автомобиль
clients -d-> addClient : Добавить клиента
contracts -d-> addContract : Добавить заказ
@enduml

